DEPARTMENTS = [
    {
        "department_id": "D001",
        "department_name": "Platform Security",
        "cost_center": "CC-1100",
        "executive_owner": "Anika Rao",
    },
    {
        "department_id": "D002",
        "department_name": "Finance Engineering",
        "cost_center": "CC-2100",
        "executive_owner": "Marcus Lee",
    },
    {
        "department_id": "D003",
        "department_name": "Applied AI",
        "cost_center": "CC-3100",
        "executive_owner": "Priya Natarajan",
    },
    {
        "department_id": "D004",
        "department_name": "Legal Operations",
        "cost_center": "CC-4100",
        "executive_owner": "Julian Park",
    },
]

EMPLOYEES = [
    {
        "employee_id": "E1001",
        "first_name": "Ava",
        "last_name": "Patel",
        "email": "ava.patel@guardianstream.dev",
        "department_id": "D001",
        "title": "Staff Security Engineer",
        "region": "US",
        "employment_status": "ACTIVE",
        "manager_id": "E1005",
        "hire_date": "2021-02-16",
        "clearance_level": "L4",
    },
    {
        "employee_id": "E1002",
        "first_name": "Noah",
        "last_name": "Kim",
        "email": "noah.kim@guardianstream.dev",
        "department_id": "D002",
        "title": "Senior Analytics Engineer",
        "region": "US",
        "employment_status": "ACTIVE",
        "manager_id": "E1006",
        "hire_date": "2022-08-01",
        "clearance_level": "L3",
    },
    {
        "employee_id": "E1003",
        "first_name": "Mia",
        "last_name": "Santos",
        "email": "mia.santos@guardianstream.dev",
        "department_id": "D003",
        "title": "Applied AI Engineer",
        "region": "US",
        "employment_status": "ACTIVE",
        "manager_id": "E1007",
        "hire_date": "2023-01-09",
        "clearance_level": "L3",
    },
    {
        "employee_id": "E1004",
        "first_name": "Lucas",
        "last_name": "Meyer",
        "email": "lucas.meyer@guardianstream.dev",
        "department_id": "D004",
        "title": "Legal Operations Analyst",
        "region": "DE",
        "employment_status": "ACTIVE",
        "manager_id": "E1008",
        "hire_date": "2021-11-15",
        "clearance_level": "L2",
    },
    {
        "employee_id": "E1005",
        "first_name": "Iris",
        "last_name": "Nguyen",
        "email": "iris.nguyen@guardianstream.dev",
        "department_id": "D001",
        "title": "Director of Platform Security",
        "region": "US",
        "employment_status": "ACTIVE",
        "manager_id": None,
        "hire_date": "2019-06-10",
        "clearance_level": "L5",
    },
    {
        "employee_id": "E1006",
        "first_name": "Owen",
        "last_name": "Brooks",
        "email": "owen.brooks@guardianstream.dev",
        "department_id": "D002",
        "title": "Director of Finance Engineering",
        "region": "US",
        "employment_status": "ACTIVE",
        "manager_id": None,
        "hire_date": "2018-09-24",
        "clearance_level": "L4",
    },
    {
        "employee_id": "E1007",
        "first_name": "Sophia",
        "last_name": "Raman",
        "email": "sophia.raman@guardianstream.dev",
        "department_id": "D003",
        "title": "Director of Applied AI",
        "region": "US",
        "employment_status": "ACTIVE",
        "manager_id": None,
        "hire_date": "2020-04-06",
        "clearance_level": "L5",
    },
    {
        "employee_id": "E1008",
        "first_name": "Ethan",
        "last_name": "Cole",
        "email": "ethan.cole@guardianstream.dev",
        "department_id": "D004",
        "title": "Associate General Counsel",
        "region": "US",
        "employment_status": "ACTIVE",
        "manager_id": None,
        "hire_date": "2017-05-19",
        "clearance_level": "L4",
    },
]

PROJECTS = [
    {
        "project_id": "P2001",
        "project_name": "Atlas Ledger",
        "project_code": "FIN-L3-ATLAS",
        "owning_department_id": "D002",
        "business_domain": "financial-reporting",
        "sensitivity_level": "L3",
        "status": "ACTIVE",
    },
    {
        "project_id": "P2002",
        "project_name": "Helios AI",
        "project_code": "AI-L4-HELIOS",
        "owning_department_id": "D003",
        "business_domain": "generative-ai",
        "sensitivity_level": "L4",
        "status": "ACTIVE",
    },
    {
        "project_id": "P2003",
        "project_name": "Project Redwood",
        "project_code": "SEC-L5-REDWOOD",
        "owning_department_id": "D001",
        "business_domain": "threat-detection",
        "sensitivity_level": "L5",
        "status": "RESTRICTED",
    },
    {
        "project_id": "P2004",
        "project_name": "CaseBridge",
        "project_code": "LEG-L2-CASE",
        "owning_department_id": "D004",
        "business_domain": "legal-operations",
        "sensitivity_level": "L2",
        "status": "ACTIVE",
    },
]

EMPLOYEE_PROJECT_ACCESS = [
    {
        "access_id": "A3001",
        "employee_id": "E1001",
        "project_id": "P2003",
        "access_role": "OWNER",
        "granted_by": "E1005",
        "granted_at": "2025-01-03 09:00:00",
        "expires_at": None,
    },
    {
        "access_id": "A3002",
        "employee_id": "E1003",
        "project_id": "P2002",
        "access_role": "EDITOR",
        "granted_by": "E1007",
        "granted_at": "2025-01-04 10:30:00",
        "expires_at": None,
    },
    {
        "access_id": "A3003",
        "employee_id": "E1002",
        "project_id": "P2001",
        "access_role": "ANALYST",
        "granted_by": "E1006",
        "granted_at": "2025-01-04 11:00:00",
        "expires_at": None,
    },
    {
        "access_id": "A3004",
        "employee_id": "E1004",
        "project_id": "P2004",
        "access_role": "REVIEWER",
        "granted_by": "E1008",
        "granted_at": "2025-01-05 13:00:00",
        "expires_at": None,
    },
    {
        "access_id": "A3005",
        "employee_id": "E1005",
        "project_id": "P2003",
        "access_role": "APPROVER",
        "granted_by": "E1005",
        "granted_at": "2025-01-03 09:05:00",
        "expires_at": None,
    },
    {
        "access_id": "A3006",
        "employee_id": "E1007",
        "project_id": "P2002",
        "access_role": "APPROVER",
        "granted_by": "E1007",
        "granted_at": "2025-01-04 10:35:00",
        "expires_at": None,
    },
    {
        "access_id": "A3007",
        "employee_id": "E1006",
        "project_id": "P2001",
        "access_role": "APPROVER",
        "granted_by": "E1006",
        "granted_at": "2025-01-04 11:05:00",
        "expires_at": None,
    },
]

SECURITY_POLICIES = [
    {
        "policy_id": "SP4001",
        "policy_name": "Restrict Redwood Mentions",
        "policy_type": "KEYWORD_ACCESS",
        "enforcement_scope": "PROMPT",
        "minimum_clearance": "L5",
        "blocked_pattern": "Project Redwood",
        "required_action": "BLOCK_AND_ALERT",
        "severity": "CRITICAL",
        "is_active": True,
        "updated_at": "2026-05-01 08:00:00",
    },
    {
        "policy_id": "SP4002",
        "policy_name": "Mask Email Addresses",
        "policy_type": "PII_REDACTION",
        "enforcement_scope": "PROMPT",
        "minimum_clearance": None,
        "blocked_pattern": r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}",
        "required_action": "MASK",
        "severity": "HIGH",
        "is_active": True,
        "updated_at": "2026-05-01 08:05:00",
    },
    {
        "policy_id": "SP4003",
        "policy_name": "Mask SSNs",
        "policy_type": "PII_REDACTION",
        "enforcement_scope": "PROMPT",
        "minimum_clearance": None,
        "blocked_pattern": r"\b\d{3}-\d{2}-\d{4}\b",
        "required_action": "MASK",
        "severity": "HIGH",
        "is_active": True,
        "updated_at": "2026-05-01 08:06:00",
    },
    {
        "policy_id": "SP4004",
        "policy_name": "Finance Data Requires L3",
        "policy_type": "PROJECT_CLEARANCE",
        "enforcement_scope": "PROJECT",
        "minimum_clearance": "L3",
        "blocked_pattern": "Atlas Ledger",
        "required_action": "CHECK_CLEARANCE",
        "severity": "MEDIUM",
        "is_active": True,
        "updated_at": "2026-05-01 08:10:00",
    },
    {
        "policy_id": "SP4005",
        "policy_name": "AI Project Requires L4",
        "policy_type": "PROJECT_CLEARANCE",
        "enforcement_scope": "PROJECT",
        "minimum_clearance": "L4",
        "blocked_pattern": "Helios AI",
        "required_action": "CHECK_CLEARANCE",
        "severity": "HIGH",
        "is_active": True,
        "updated_at": "2026-05-01 08:11:00",
    },
]

AUDIT_LOGS = [
    {
        "audit_id": "L5001",
        "request_id": "REQ-0001",
        "employee_id": "E1002",
        "project_id": "P2001",
        "request_channel": "web",
        "original_prompt": "Summarize Atlas Ledger close metrics for q4 and send to alex@example.com",
        "sanitized_prompt": "Summarize Atlas Ledger close metrics for q4 and send to [REDACTED_EMAIL]",
        "policy_outcome": "ALLOWED_WITH_REDACTION",
        "redaction_count": 1,
        "response_status": "COMPLETED",
        "created_at": "2026-05-01 09:00:01",
    },
    {
        "audit_id": "L5002",
        "request_id": "REQ-0002",
        "employee_id": "E1003",
        "project_id": "P2002",
        "request_channel": "api",
        "original_prompt": "Give me the latest Helios AI platform highlights.",
        "sanitized_prompt": "Give me the latest Helios AI platform highlights.",
        "policy_outcome": "ALLOWED",
        "redaction_count": 0,
        "response_status": "COMPLETED",
        "created_at": "2026-05-01 09:02:14",
    },
    {
        "audit_id": "L5003",
        "request_id": "REQ-0003",
        "employee_id": "E1004",
        "project_id": "P2003",
        "request_channel": "web",
        "original_prompt": "Tell me about Project Redwood deployment plans.",
        "sanitized_prompt": "Tell me about Project Redwood deployment plans.",
        "policy_outcome": "BLOCKED_CLEARANCE",
        "redaction_count": 0,
        "response_status": "DENIED",
        "created_at": "2026-05-01 09:05:42",
    },
    {
        "audit_id": "L5004",
        "request_id": "REQ-0004",
        "employee_id": "E1001",
        "project_id": "P2003",
        "request_channel": "web",
        "original_prompt": "Review the latest Project Redwood incident summary for 123-45-6789.",
        "sanitized_prompt": "Review the latest Project Redwood incident summary for [REDACTED_SSN].",
        "policy_outcome": "ALLOWED_WITH_REDACTION",
        "redaction_count": 1,
        "response_status": "COMPLETED",
        "created_at": "2026-05-01 09:07:33",
    },
]

REQUEST_METRICS = [
    {
        "metric_id": "M6001",
        "request_id": "REQ-0001",
        "gateway_latency_ms": 84.50,
        "agent_latency_ms": 412.32,
        "total_latency_ms": 496.82,
        "token_usage_input": 1240,
        "token_usage_output": 280,
        "blocked_attack": False,
        "created_at": "2026-05-01 09:00:01",
    },
    {
        "metric_id": "M6002",
        "request_id": "REQ-0002",
        "gateway_latency_ms": 62.14,
        "agent_latency_ms": 355.90,
        "total_latency_ms": 418.04,
        "token_usage_input": 980,
        "token_usage_output": 245,
        "blocked_attack": False,
        "created_at": "2026-05-01 09:02:14",
    },
    {
        "metric_id": "M6003",
        "request_id": "REQ-0003",
        "gateway_latency_ms": 48.11,
        "agent_latency_ms": 0.00,
        "total_latency_ms": 48.11,
        "token_usage_input": 410,
        "token_usage_output": 0,
        "blocked_attack": True,
        "created_at": "2026-05-01 09:05:42",
    },
    {
        "metric_id": "M6004",
        "request_id": "REQ-0004",
        "gateway_latency_ms": 97.80,
        "agent_latency_ms": 501.23,
        "total_latency_ms": 599.03,
        "token_usage_input": 1505,
        "token_usage_output": 320,
        "blocked_attack": False,
        "created_at": "2026-05-01 09:07:33",
    },
]
